#!/bin/sh

while getopts h: flag
do 
	case "${flag}" in 
		h) host=${OPTARG};; 
	esac done

nmap -sT -p- -T4 -Pn $host | tee pt_recon

grep -oP "[0-9]+?(?=\/)" pt_recon > pt_tmp
tr '\n' , <pt_tmp > pt

rm pt_recon 

nmap -A -T4 -p $(cat pt) $host | tee tcp-scan

rm pt
